# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  COMPOSER_VERSION: "2.1.12"

default:
  image: composer:$COMPOSER_VERSION

stages:
  - build
  - test

composer:
  stage: build
  interruptible: true
  cache:
    key: composer-${CI_COMMIT_REF_SLUG}
    paths:
      - .composer-cache/
  script:
    - composer config -g cache-dir "$(pwd)/.composer-cache"
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - composer dump-autoload
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/

sast:
  stage: test

phpunit:
  stage: test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
  interruptible: true
  script:
    - composer test
  artifacts:
    expire_in: 1 day
    paths:
      - build/

version_watch:
  stage: test
  interruptible: true
  allow_failure: true
  script:
    - composer outdated -D --strict
